In [2]:
my_list = [1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
mat = np.array(my_mat)

In [12]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros((5, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [20]:
np.ones((3, 4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
np.linspace(0, 5, 10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [24]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [33]:
np.random.rand(5)

array([ 0.80434072,  0.82368814,  0.79795934,  0.81312796,  0.19447666])

In [36]:
np.random.randn(2)

array([-1.42104196, -0.60342549])

In [44]:
np.random.randint(1, 100)

61

In [46]:
arr = np.arange(25)

In [48]:
ranarr = np.random.randint(0, 50, 10)

In [56]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
ranarr.max()

48

In [62]:
ranarr.min()

3

In [63]:
ranarr

array([43, 48, 27, 11,  3, 23, 26, 41, 36, 34])

In [65]:
ranarr.argmax()

1

In [66]:
ranarr.argmin()

4

In [68]:
arr.reshape(5, 5).shape

(5L, 5L)

In [69]:
arr.dtype

dtype('int32')