In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:3] = 100

In [11]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0, 11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[:6]

In [16]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:] = 99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy()

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [25]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:] = 100

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [32]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[0][0]

5

In [34]:
arr_2d[0]

array([ 5, 10, 15])

In [35]:
arr_2d[0, 0]

5

In [36]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [41]:
arr = np.arange(1, 11)

In [42]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [43]:
bool_arr = arr > 5

In [44]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])